server.port=8081
spring.application.name=user-service

spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:3306/user_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret (Base64 encoded key)
jwt.secret=def50200845a70cc3be589c3bc88383f089606d5c6439e6ad27fa2818625ba48a733792015ffb9691866dfcf6cb33b7b51b326305a49
jwt.expiration=86400000
