server.port=8085
spring.application.name=order-service

spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:3306/order_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Internal Microservices Base URLs
services.marketplace.url=http://${MARKETPLACE_SERVICE_HOST:localhost}:8084/api/marketplace/products
services.payment.url=http://${PAYMENT_SERVICE_HOST:localhost}:8087/api/payments
services.transport.url=http://${TRANSPORT_SERVICE_HOST:localhost}:8088/api/transport
services.notification.url=http://${NOTIFICATION_SERVICE_HOST:localhost}:8089/api/notifications

# Camunda BPM Engine & Web Cockpit Configuration
camunda.bpm.auto-deployment-enabled=true
camunda.bpm.generic-properties.properties.historyTimeToLive=P180D
camunda.bpm.admin-user.id=demo
camunda.bpm.admin-user.password=demo
camunda.bpm.admin-user.first-name=Admin
camunda.bpm.admin-user.last-name=User

# JWT Security Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

